<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>404 Error</title>

    <link href="<?php echo URL; ?>public/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo URL; ?>public/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="<?php echo URL; ?>public/css/animate.css" rel="stylesheet">
    <link href="<?php echo URL; ?>public/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">


    <div class="middle-box text-center animated fadeInDown">
        <h1>404</h1>
        <h3 class="font-bold">Ocorreu um erro inesperado!</h3>

        <div class="error-desc">
            A pagina que você deseja acessar não existe.<br/>
            Volte para a pagina principal: <br/><a href="<?php echo URL;?>" class="btn btn-primary m-t">Pagina Principal</a>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?php echo URL; ?>public/js/jquery-2.1.1.js"></script>
    <script src="<?php echo URL; ?>public/js/bootstrap.min.js"></script>

</body>
</html>
